Repository SR5-FoundryVTT/SR5-FoundryVTT, pull requests merged in 2023-11, with the labels that each got.

#868 Updated esbuild and typecheck
  gulp.tasks.js
  package-lock.json
  package.json
Labels: code

#867 fix thermographic detection not reacting to heat
  src/module/vision/astralPerception/astralPerceptionBackgroundShader.ts
  src/module/vision/augmentedReality/arDetectionMode.ts
  src/module/vision/lowlightVision/lowlightDetectionMode.ts
  src/module/vision/lowlightVision/lowlightFilter.ts
  src/module/vision/thermographicVision/thermographicDetectionMode.ts
  src/module/vision/visionConfigurator.ts
Labels: enhancement

#819 add opposed ritual spellcasting
  public/icons/importer/ritual/ritual.svg
  public/locale/de/config.json
  public/locale/en/config.json
  public/locale/fr/config.json
  public/locale/ko/config.json
  public/locale/pt-BR/config.json
  src/module/actor/sheets/SR5CharacterSheet.ts
  src/module/apps/characterImport/importHelper/ItemsParser.js
  src/module/apps/characterImport/magicImport/RitualParser.js
  src/module/apps/characterImport/magicImport/SpellParser.js
  src/module/config.ts
  src/module/handlebars/HandlebarTemplates.ts
  src/module/handlebars/ItemLineHelpers.ts
  src/module/hooks.ts
  src/module/item/ChatData.ts
  src/module/rules/RitualRules.ts
  src/module/tests/OpposedRitualTest.ts
  src/module/tests/RitualSpellcastingTest.ts
  src/templates/actor/parts/magic/RitualList.html
  src/templates/actor/tabs/MagicTab.html
  src/templates/apps/dialogs/ritualspellcasting-test-dialog.html
  src/templates/item/parts/ritual.html
  src/templates/item/ritual.html
  template.json
Labels: enhancement

#903 add hardened armor to spirits
  src/module/actor/prep/SpiritPrep.ts
Labels: enhancement

#918 Apply Hardened armor rules during physical defense test
  public/locale/en/config.json
  src/module/actor/SR5Actor.ts
  src/module/rules/CombatRules.ts
  src/module/tests/PhysicalDefenseTest.ts
  src/unittests/sr5.AttackTests.spec.ts
Labels: enhancement

#896 Mark imports for review
  public/icons/checklist-white.svg
  public/icons/checklist.svg
  public/icons/importer/icon attribution.txt
  public/locale/en/config.json
  src/css/actor.scss
  src/css/bundle.scss
  src/css/config/_variables.scss
  src/css/item.scss
  src/module/actor/sheets/SR5BaseActorSheet.ts
  src/module/constants.ts
  src/module/handlebars/BasicHelpers.ts
  src/module/handlebars/HandlebarTemplates.ts
  src/module/importer/importer/DataImporter.ts
  src/module/item/SR5ItemSheet.ts
  src/module/settings.ts
  src/templates/actor/character.html
  src/templates/actor/ic.html
  src/templates/actor/parts/ToggleImportFlags.html
  src/templates/actor/tabs/MiscTab.html
  src/templates/actor/tabs/ic/ICMiscTab.html
  src/templates/common/List/ListItem.html
  src/templates/item/parts/header.html
  src/templates/item/parts/import_flag_button.html
Labels: enhancement

#919 [CODE] first set of chummer character importer tests
  src/module/apps/characterImport/CharacterImporter.js
  src/module/apps/characterImport/CharacterInfoUpdater.js
  src/module/apps/characterImport/ItemsParser.js
  src/unittests/characterImport/sr5.CharacterImporter.spec.ts
  src/unittests/characterImport/sr5.CharacterInfoUpdater.spec.ts
  src/unittests/quench.ts
Labels: code

#923 [FEATURE] Vehicles import mounted weapons
  src/module/apps/characterImport/vehicleImport/MountedWeaponParser.js
  src/module/apps/characterImport/vehicleImport/VehicleParser.js
  src/module/apps/characterImport/weaponImport/WeaponParser.js
  src/unittests/characterImport/sr5.CharacterImporterWeapon.spec.ts
  src/unittests/characterImport/sr5.VehicleImporterMountedWeapon.spec.ts
  src/unittests/quench.ts
  src/unittests/sr5.WeaponParser.spec.ts
Labels: enhancement

#925 [FEATURE] Add group option to contacts
  public/locale/en/config.json
  src/module/types/item/Contact.ts
  src/templates/item/parts/contact.html
  template.json
Labels: enhancement

#931 [BUG] Allow initiation rank to be used as limit in actions
  public/locale/en/config.json
  src/module/actor/SR5Actor.ts
  src/module/actor/prep/functions/LimitsPrep.ts
  src/module/apps/characterImport/magicImport/InitiationParser.js
  src/module/migrator/VersionMigration.ts
  src/module/migrator/versions/Version0_16_0.ts
  src/module/rules/LimitRules.ts
  src/module/types/actor/Common.ts
  template.json
Labels: bug

#858 [CODE] Refactor/item data prep
  src/module/data/DataDefaults.ts
  src/module/item/SR5Item.ts
  src/module/item/prep/AdeptPowerPrep.ts
  src/module/item/prep/SinPrep.ts
  src/module/item/prep/functions/ActionPrep.ts
  src/module/item/prep/functions/RangePrep.ts
  src/module/item/prep/functions/TechnologyPrep.ts
  src/module/migrator/Migrator.ts
  src/module/migrator/VersionMigration.ts
  src/module/types/global.d.ts
  src/module/types/template/Technology.ts
  src/unittests/quench.ts
  src/unittests/sr5.ItemDataPrep.spec.ts
Labels: code

#942 [BUG] Character Import. Qualities and Equipment import issues
  src/module/apps/characterImport/bioImport/QualityParser.js
  src/module/apps/characterImport/importHelper/BaseGearParser.ts
Labels: bug

#959 [FEATURE] Mark actor as defeated when taken enough damage
  src/module/actor/SR5Actor.ts
  src/module/actor/flows/DamageApplicationFlow.ts
  src/module/actor/sheets/SR5BaseActorSheet.ts
  src/module/rules/ConditionRules.ts
Labels: enhancement

#954 [LAYOUT] Show initiategrad in sheet ui
  src/templates/actor/tabs/MiscTab.html
Labels: design

#965 [CODE] Split technomancer from magic
  src/module/apps/characterImport/CharacterInfoUpdater.js
  src/module/apps/characterImport/magicImport/InitiationParser.js
  src/module/apps/characterImport/technoImport/SubmersionParser.js
  src/module/types/actor/Character.ts
  src/module/types/actor/Common.ts
  template.json
Labels: code

#964 [TOUR] Condition tracks and natural recovery
  gulp.tasks.js
  public/locale/en/config.json
  src/module/hooks.ts
  src/module/tours/jsons/tracks.json
  src/module/tours/sr5Tours.ts
  src/module/tours/tours.ts
  src/templates/actor/character.html
  src/templates/common/HorizontalCellInput.html
Labels: enhancement

#970 [BUG] RangedAttackTest did filter actor uuids using token uuids
  src/module/tests/RangedAttackTest.ts
  src/module/tests/SuccessTest.ts
  src/module/types/global.d.ts
  src/module/types/template/weapon.ts
Labels: bug

#951 [FEATURE] Vehicles take assign Icons from character import
  src/module/apps/characterImport/vehicleImport/VehicleParser.js
Labels: enhancement

#971 [TOUR] Track Tour => Condition Monitor Tour AND tour actor creation
  public/locale/en/config.json
  src/module/tours/jsons/ConditionMonitor.json
  src/module/tours/jsons/character-import.json
  src/module/tours/jsons/tracks.json
  src/module/tours/sr5Tours.ts
  src/module/tours/tours.ts
Labels: enhancement

#993 [BUG] Commlink PAN breaks items when used in conjunction with Compendium
  src/module/actor/sheets/SR5VehicleActorSheet.ts
  src/module/item/SR5Item.ts
  src/module/item/SR5ItemSheet.ts
  src/module/item/flows/NetworkDeviceFlow.ts
  src/unittests/sr5.NetworkDevices.spec.ts
Labels: bug

#957 [FEATURE] Show icon and split successes for hardened armor
  public/locale/en/config.json
  src/css/bundle.scss
  src/css/chat.scss
  src/module/actor/prep/functions/ItemPrep.ts
  src/module/data/SR5ItemDataWrapper.ts
  src/module/rules/CombatRules.ts
  src/module/rules/SoakRules.ts
  src/module/tests/PhysicalResistTest.ts
  src/module/tests/SuccessTest.ts
  src/templates/apps/dialogs/parts/success-test-common.html
  src/templates/rolls/success-test-message.html
Labels: bug, enhancement
