Repository SR5-FoundryVTT/SR5-FoundryVTT, pull requests merged in 2023-12, with the labels that each got.

#1032 [BUG] Do Not Force Center In Tables
  src/css/foundry.scss
Labels: bug

#1025 Feature/fix Layout Issues Actor & Items
  src/css/actor.scss
  src/css/item.scss
  src/templates/actor/parts/attributes/FakeAttribute.html
Labels: bug

#1022 [BUG] Fix key binding tooltip and convert to upper case
  src/module/actor/sheets/SR5BaseActorSheet.ts
  src/templates/common/List/ListItem.html
Labels: bug

#1029 [FEATURE] Add Seats Stat to Vehicles
  public/locale/en/config.json
  src/module/actor/prep/VehiclePrep.ts
  src/module/apps/characterImport/CharacterImporter.js
  src/module/apps/characterImport/vehicleImport/VehicleParser.ts
  src/module/config.ts
  src/module/types/actor/Vehicle.ts
  src/templates/actor/parts/vehicle/VehicleStatsList.html
  src/unittests/characterImport/drone.json
  src/unittests/characterImport/sr5.VehicleImporter.spec.ts
  src/unittests/characterImport/sr5.VehicleImporterMountedWeapon.spec.ts
  src/unittests/characterImport/vehicle.json
  src/unittests/quench.ts
  src/unittests/utils.ts
  template.json
Labels: enhancement

#1030 [FEATURE] Add ESLint and Prettier
  .editorconfig
  .eslintrc
  .eslintrc.js
  .github/workflows/test.yml
  .prettierignore
  .prettierrc
  README-DEV.md
  package-lock.json
  package.json
Labels: code

#986 [Feature] first look for targeted tokens, then selected when creating…
  src/module/tests/TestCreator.ts
Labels: enhancement

#1060 [FEATURE] ActiveEffects rework to improve effect capabilities
  public/locale/de/config.json
  public/locale/en/config.json
  public/locale/ko/config.json
  src/module/actor/SR5Actor.ts
  src/module/actor/flows/ModifierFlow.ts
  src/module/actor/sheets/SR5BaseActorSheet.ts
  src/module/chatMessage/SR5ChatMessage.ts
  src/module/config.ts
  src/module/constants.ts
  src/module/data/SR5ItemDataWrapper.ts
  src/module/effect/SR5ActiveEffect.ts
  src/module/effect/SR5ActiveEffectConfig.ts
  src/module/effect/autoinline/AutocompleteInlineHooksFlow.ts
  src/module/effect/flows/EnvironmentalChangeFlow.ts
  src/module/effect/flows/SituationModifierEffectsFlow.ts
  src/module/effect/flows/SuccessTestEffectsFlow.ts
  src/module/effects.ts
  src/module/handlebars/ItemLineHelpers.ts
  src/module/hooks.ts
  src/module/item/SR5Item.ts
  src/module/item/SR5ItemSheet.ts
  src/module/item/flows/ActionFlow.ts
  src/module/migrator/Migrator.ts
  src/module/migrator/VersionMigration.ts
  src/module/migrator/versions/Version0_16_0.ts
  src/module/migrator/versions/Version0_18_0.ts
  src/module/migrator/versions/Version0_8_0.ts
  src/module/rules/DocumentSituationModifiers.ts
  src/module/rules/modifiers/SituationModifier.ts
  src/module/sockets.ts
  src/module/tests/OpposedTest.ts
  src/module/tests/RangedAttackTest.ts
  src/module/tests/SkillTest.ts
  src/module/tests/SuccessTest.ts
  src/module/tests/TestCreator.ts
  src/module/types/effect/ActiveEffect.ts
  src/module/types/global.d.ts
  src/module/types/sheets/ActorSheet.ts
  src/module/utils/sheets.ts
  src/templates/actor/tabs/EffectsTab.html
  src/templates/apps/migrator/Version0.18.0.hbs
  src/templates/chat/test-effects-message.hbs
  src/templates/effect/active-effect-config.html
  src/unittests/sr5.ActiveEffect.spec.ts
  system.json
Labels: enhancement
