Repository SR5-FoundryVTT/SR5-FoundryVTT, pull requests merged in 2023-10, with the labels that each got.

#802 fix handling of multiple skill specs
  src/module/apps/characterImport/BaseParserFunctions.js
  src/module/apps/characterImport/CharacterInfoUpdater.js
Labels: bug

#805 Feature/importer overwrites character
  src/module/actor/prep/functions/SkillsPrep.ts
  src/module/actor/sheets/SR5BaseActorSheet.ts
  src/module/apps/characterImport/CharacterImporter.js
  src/module/apps/characterImport/CharacterInfoUpdater.js
  src/module/apps/characterImport/ItemsParser.js
Labels: enhancement

#804 Allow vehicles to be added to PANs and improve matrix device item edit page
  src/css/item.scss
  src/module/actor/SR5Actor.ts
  src/module/actor/sheets/SR5VehicleActorSheet.ts
  src/module/item/ChatData.ts
  src/module/item/SR5Item.ts
  src/module/item/SR5ItemSheet.ts
  src/module/item/flows/NetworkDeviceFlow.ts
  src/module/types/actor/Vehicle.ts
  src/templates/actor/parts/vehicle/VehicleSecondStatsList.html
  src/templates/actor/tabs/NetworkTab.html
  src/templates/item/parts/matrix.html
  src/unittests/sr5.NetworkDevices.spec.ts
Labels: enhancement

#825 fix weapon stats and minimal clip handling + fix for grenades
  src/module/apps/characterImport/WeaponParser.js
  src/module/apps/characterImport/armorImport/ArmorParser.js
  src/module/apps/characterImport/bioImport/ContactParser.js
  src/module/apps/characterImport/bioImport/LifestyleParser.js
  src/module/apps/characterImport/bioImport/QualityParser.js
  src/module/apps/characterImport/bioImport/SinParser.ts
  src/module/apps/characterImport/importHelper/BaseGearParser.ts
  src/module/apps/characterImport/importHelper/BaseParserFunctions.js
  src/module/apps/characterImport/importHelper/GearsParser.ts
  src/module/apps/characterImport/importHelper/ItemsParser.js
  src/module/apps/characterImport/importHelper/ParserSelector.ts
  src/module/apps/characterImport/magicImport/PowerParser.js
  src/module/apps/characterImport/magicImport/SpellParser.js
  src/module/apps/characterImport/matrixImport/DeviceParser.ts
  src/module/apps/characterImport/matrixImport/ProgramParser.ts
  src/module/apps/characterImport/wareImport/WareParser.js
  src/module/apps/characterImport/weaponImport/AmmoParser.ts
  src/module/apps/characterImport/weaponImport/WeaponParser.js
Labels: bug, enhancement

#829 Feature/add vision checks
  src/module/actor/prep/CharacterPrep.ts
  src/module/actor/prep/CritterPrep.ts
  src/module/actor/prep/ICPrep.ts
  src/module/actor/prep/SpiritPrep.ts
  src/module/actor/prep/SpritePrep.ts
  src/module/actor/prep/VehiclePrep.ts
  src/module/actor/prep/functions/VisibilityChecksPrep.ts
  src/module/types/actor/Common.ts
  src/module/vision/astralPerception/astralPerceptionDetectionMode.ts
  src/module/vision/augmentedReality/arDetectionMode.ts
  src/module/vision/lowlightVision/lowlightDetectionMode.ts
  src/module/vision/thermographicVision/thermographicDetectionMode.ts
  src/unittests/sr5.ActorDataPrep.spec.ts
  template.json
Labels: enhancement

#841 fix missing signs in clip ammo
  src/module/apps/characterImport/CharacterImporter.js
  src/module/apps/characterImport/CharacterInfoUpdater.js
  src/module/apps/characterImport/armorImport/ArmorParser.js
  src/module/apps/characterImport/importHelper/ItemsParser.js
  src/module/apps/characterImport/magicImport/CritterPowerParser.js
  src/module/apps/characterImport/weaponImport/WeaponParser.js
  template.json
Labels: chummer

#856 Replaced old repo url
  README.md
  src/templates/apps/changelog.html
  src/templates/effect/active-effect-config.html
  system.json
Labels: code

#838 add item + import for metamagics and echos
  public/icons/importer/echo.svg
  public/icons/importer/icon attribution.txt
  public/icons/importer/metamagic.svg
  public/locale/en/config.json
  src/module/actor/sheets/SR5BaseActorSheet.ts
  src/module/actor/sheets/SR5CharacterSheet.ts
  src/module/apps/characterImport/CharacterInfoUpdater.js
  src/module/apps/characterImport/importHelper/ItemsParser.js
  src/module/apps/characterImport/importHelper/SimpleParser.js
  src/module/apps/characterImport/magicImport/MetamagicParser.js
  src/module/config.ts
  src/module/handlebars/HandlebarTemplates.ts
  src/module/handlebars/ItemLineHelpers.ts
  src/module/types/ShadowrunItemData.ts
  src/module/types/item/Echo.ts
  src/module/types/item/Metamagic.ts
  src/templates/actor/parts/magic/MetamagicList.html
  src/templates/actor/parts/matrix/EchoList.html
  src/templates/actor/tabs/BioTab.html
  src/templates/item/echo.html
  src/templates/item/metamagic.html
  template.json
Labels: enhancement
